<?xml version="1.0" encoding="utf-8" ?>
<test-results date="YYYY-MM-DD" time="HH:MM:SS" name="Results" total="5" failures="2" not-run="2" errors="0" inconclusive="0" ignored="0" skipped="0" invalid="0">
    <environment nunit-version="2.6.4" clr-version="[clr-version]" os-version="[os-version]" platform="[platform]" cwd="[cwd]" machine-name="[machine-name]" user="[user]" user-domain="[user-domain]" />
    <culture-info current-culture="[current-culture]" current-uiculture="[current-uiculture]" />
    <test-suite type="Assembly" success="false" name="[assemblyLocation]" time="1.234" executed="true" result="Failure">
        <results>
            <test-suite type="TestFixture" name="Fixie.Tests.Execution.Listeners.NUnitXmlTests+PassFailTestClass" success="false" time="1.234" executed="true" result="Failure">
                <results>
                  <test-case name="Fixie.Tests.Execution.Listeners.NUnitXmlTests+PassFailTestClass.SkipWithReason" executed="false" success="true" result="Ignored">
                    <reason>
                      <message><![CDATA[reason]]></message>
                    </reason>
                  </test-case>
                  <test-case name="Fixie.Tests.Execution.Listeners.NUnitXmlTests+PassFailTestClass.SkipWithoutReason" executed="false" success="true" result="Ignored" />
                  <test-case name="Fixie.Tests.Execution.Listeners.NUnitXmlTests+PassFailTestClass.Fail" executed="true" success="false" result="Failure" time="1.234">
                    <failure>
                      <message><![CDATA['Fail' failed!]]></message>
                      <stack-trace>
                        <![CDATA[Fixie.Tests.FailureException
'Fail' failed!
   at Fixie.Tests.Execution.Listeners.NUnitXmlTests.PassFailTestClass.Fail() in [fileLocation]:line #]]></stack-trace>
                    </failure>
                  </test-case>
                  <test-case name="Fixie.Tests.Execution.Listeners.NUnitXmlTests+PassFailTestClass.FailByAssertion" executed="true" success="false" result="Failure" time="1.234">
                    <failure>
                      <message><![CDATA[Assert.Equal() Failure
Expected: 2
Actual:   1]]></message>
                      <stack-trace><![CDATA[Should.Core.Exceptions.EqualException
Assert.Equal() Failure
Expected: 2
Actual:   1
   at Fixie.Tests.Execution.Listeners.NUnitXmlTests.PassFailTestClass.FailByAssertion() in [fileLocation]:line #]]></stack-trace>
                    </failure>
                  </test-case>
                  <test-case name="Fixie.Tests.Execution.Listeners.NUnitXmlTests+PassFailTestClass.Pass" executed="true" success="true" result="Success" time="1.234" />
                </results>
            </test-suite>
        </results>
    </test-suite>
</test-results>



